<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>LNU - IDS</title>

  @include('layouts.stylesheet')

</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">
    <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('assets/images/logo/lnu_logo.png') }}" alt="IDSLogo" height="150" width="150">
  </div>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <div class="content">
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-info card-outline">
            <div class="card-body {{$bg_color}}">
              <div class="row">
                <div class="col-lg-2">
                  <input type="hidden" id="payroll_id" value="{{$payroll_id}}">
                  @php
                    $payrollHide = '';
                  @endphp
                  @if($query->generate_option=='partial')
                    @php
                      $payrollHide = 'hide';
                    @endphp
                    <button class="btn btn-success btn-success-scan btn-sm" name="generate"><span class="fa fa-check"></span> Generate Payroll</button>
                  @endif
                </div>
                <div class="col-lg-8 center">
                  <h5>Payroll
                        @php
                        if(count($query->months)>0){
                            $payroll_name = 'Part-Time';
                        }else{
                            $payroll_name = $query->payroll_type->name;
                        }
                        @endphp
                        {{$payroll_name}}<br>
                        {{date('F',strtotime($query->year.'-'.$query->month.'-01')).' '.$query->day_from.'-'.$query->day_to.', '.$query->year}}</h5>
                </div>
                <div class="col-lg-12"><br>
                  Generated By: <label>{{$query->get_generated_by->lastname}}, {{$query->get_generated_by->firstname}}</label><br>
                  Date Time Generated: <label>{{date('M d, Y h:ia',strtotime($query->generated_at))}}</label>
                </div>
              </div>
            </div>
          </div><!-- /.card -->
        </div>
        <!-- /.col-md-6 -->
        <div class="col-lg-12">
          <div class="card card-primary card-outline">
            <div class="card-body {{$bg_color}}">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="row">
                          <div class="col-lg-8 hide" id="addEmployeeDiv">
                            <div class="input-group">
                              <div id="employeePayroll" style="width: 60%">
                                <select class="form-control select2 employeePayrollSearch" style="width: 100%">
                                  <option value=""></option>
                                </select>
                              </div>
                              <div class="input-group-append">
                                <button class="btn btn-info btn-info-scan" name="addEmployeeSubmit">
                                  <span class="fa fa-check"></span>
                                </button>
                                <button class="btn btn-danger btn-danger-scan" name="addEmployeeDivHide">
                                  <span class="fa fa-minus"></span>
                                </button>
                              </div>
                            </div>
                          </div>
                          <div class="col-lg-4">
                            <button class="btn btn-info btn-info-scan btn-sm" name="addEmployeeDisplay">
                              <span class="fa fa-plus"></span> Add Employee
                            </button>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-6">
                        <form method="GET" target="_blank">
                          <button class="btn btn-primary btn-primary-scan btn-sm {{$payrollHide}}"
                            formaction="{{ route('pdf.view', ['pdf_option' => $pdf_option]) }}" style="float:right;">
                            <span class="fa fa-print"></span> Payroll
                          </button>
                          {{-- <button class="btn btn-info btn-primary-scan btn-sm {{$payrollHide}}" id="dvPrintModal" style="float:right;">
                            <span class="fa fa-print"></span> DV
                          </button>
                          <button class="btn btn-primary btn-primary-scan btn-sm {{$payrollHide}}" id="orsPrintModal" style="float:right;">
                            <span class="fa fa-print"></span> ORS
                          </button> --}}
                        </form>
                      </div>
                    </div>
                  </div>
                    <div class="col-lg-12">
                      <br><br>
                        <table id="listTable" class="table table-bordered table-fixed"
                                data-toggle="table"
                                data-search="true"
                                data-height="600"
                                data-buttons-class="primary"
                                data-show-export="true"
                                data-show-columns-toggle-all="true"
                                data-mobile-responsive="true"
                                data-pagination="true"
                                data-page-size="5"
                                data-page-list="[5, 50, 100, All]"
                                data-loading-template="loadingTemplate"
                                data-export-types="['csv', 'txt', 'doc', 'excel', 'json', 'sql']">
                            <thead style="font-size:12px;">
                                <tr>
                                    <th data-field="f1" data-sortable="true" data-align="center" rowspan="2">#</th>
                                    <th data-field="f2" data-align="center" rowspan="2">

                                    </th>
                                    <th data-field="name" data-sortable="true" data-align="center" rowspan="2">Name</th>
                                    <th data-field="position" data-sortable="true" data-align="center" rowspan="2">Position</th>
                                    <th data-field="salary" data-sortable="true" data-align="center" rowspan="2">Salary</th>
                                    @if($query->payroll_type->w_salary=='Yes' && $query->payroll_type->w_salary_name!=NULL)
                                    <th data-field="w_salary_amount" data-sortable="true" data-align="center">{{$query->payroll_type->w_salary_name}}</th>
                                    @endif
                                    @if($query->payroll_type->column_name!=NULL)
                                    <th data-field="column_amount" data-sortable="true" data-align="center">{{$query->payroll_type->column_name}}</th>
                                    @endif
                                    @if($query->payroll_type->column_name2!=NULL)
                                    <th data-field="column_amount2" data-sortable="true" data-align="center">{{$query->payroll_type->column_name2}}</th>
                                    @endif
                                    @if(count($query->months)>0)
                                        <th data-align="center" colspan="{{count($query->months)}}">Months</th>
                                    @endif
                                    @if(count($query->unclaimeds)>0)
                                        <th data-align="center" colspan="{{count($query->unclaimeds)}}">Unclaimed ({{$query->year-1}})</th>
                                    @endif
                                    @if(count($query->months)>0)
                                    <th data-field="hours" data-sortable="true" data-align="center" rowspan="2">Hours</th>
                                    @endif
                                    <th data-field="earned" data-sortable="true" data-align="center" rowspan="2">Earned</th>
                                    @foreach($allowance_list as $allowance)
                                        <th data-field="allowance_{{$allowance->id}}" data-sortable="true" data-align="center" rowspan="2">{{$allowance->name}}</th>
                                    @endforeach
                                    @php
                                    if($group_count->count()>0){
                                        foreach($group_count as $deduction){
                                            $deduction_group_count[$deduction->group_id] = $deduction->count;
                                        }
                                    }
                                    @endphp
                                    @foreach($deduction_group as $group)
                                        <th data-align="center" colspan="{{$deduction_group_count[$group->id]}}">{{$group->name}}</th>
                                    @endforeach
                                    @foreach($deduction_other as $deduction)
                                        <th data-field="{{$deduction->id}}" data-sortable="true" data-align="center" rowspan="2">{{$deduction->name}}</th>
                                    @endforeach
                                    @if($query->payroll_type_id==1)
                                        <th data-field="lwop" data-sortable="true" data-align="center" rowspan="2">LWOP</th>
                                    @endif
                                    <th data-field="deduction" data-sortable="true" data-align="center" rowspan="2">Deduction</th>
                                    <th data-field="netpay" data-sortable="true" data-align="center" rowspan="2">NetPay</th>
                                </tr>
                                <tr>
                                    @foreach($query->months as $month)
                                        <th data-field="{{$month->month}}_month" data-sortable="true" data-align="center">{{date('M',strtotime($month->year.'-'.$month->month.'-01'))}}</th>
                                    @endforeach
                                    @foreach($query->unclaimeds as $month)
                                        <th data-field="{{$month->month}}_unclaimed" data-sortable="true" data-align="center">{{date('M',strtotime($month->year.'-'.$month->month.'-01'))}}</th>
                                    @endforeach
                                    @foreach($deduction_list as $deduction)
                                        <th data-field="{{$deduction->id}}" data-sortable="true" data-align="center">{{$deduction->name}}</th>
                                    @endforeach
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->

  </div>
  @include('layouts.modal')
  @include('layouts.script')
  <script src="{{ asset('assets/js/search/employeePayroll.js') }}"></script>
  <script src="{{ asset('assets/js/hrims/payroll/view/payroll_view.js') }}"></script>
</div>
<!-- ./wrapper -->

</body>


</html>
